before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: linux
    binary: notidb
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: darwin
    binary: notidb
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1

release:
  prerelease: auto
  github:
    owner: ChmaraX 
    name: notidb

universal_binaries:
  - replace: true
    id: darwin

brews:
  -
    name: notidb 
    homepage: https://github.com/ChmaraX/notidb
    tap:
      owner: ChmaraX 
      name: homebrew-chmarax
    commit_author:
      name: chmarax 
      email: adam.chmara1@gmail.com

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

